public class Concessionaria {
    
    private List<Funcionario> funcionarios;
    private List<Veiculo> veiculos;
    
/* ERRO 
    public Concessionaria() {
        funcionarios = new List<Funcionario>();
        veiculos = new List<Veiculo>();
    }

    
    
    public void adicionarFuncionario(String nome, String cpf, String matricula) {
        Funcionario novoFuncionario = new Funcionario(nome, cpf, matricula);
        funcionarios.add(novoFuncionario);
    }

  
    public void adicionarVeiculo(String marca, String modelo, String placa) {
        Veiculo novoVeiculo = new Veiculo(marca, modelo, placa);
        veiculos.add(novoVeiculo);
    }
*/
}